### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by panna19951227** [bryanyzhu/two-stream-pytorch#28]
(1)when i run train flow,it often meet out of memory in validate(epoch 23 or 47...),can you give me some advice?Thanks!!!!
(2)How to run it in multi-GPU?
:
Current learning rate is 0.001000:
Epoch: [23][120/383]	Time 10.661 (12.373)	Loss 1.7992 (1.8488)	Prec@1 47.200 (51.433)
Epoch: [23][240/383]	Time 10.836 (12.372)	Loss 1.7938 (1.8701)	Prec@1 50.400 (50.050)
Epoch: [23][360/383]	Time 10.346 (12.612)	Loss 1.9167 (1.8574)	Prec@1 52.000 (50.722)
main_single_gpu.py:282: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  input_var = torch.autograd.Variable(input, volatile=True)
main_single_gpu.py:283: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  target_var = torch.autograd.Variable(target, volatile=True)
main_single_gpu.py:291: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  losses.update(loss.data[0], input.size(0))
main_single_gpu.py:292: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  top1.update(prec1[0], input.size(0))
main_single_gpu.py:293: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  top3.update(prec3[0], input.size(0))
**Test: [0/152]	Time 18.244 (18.244)	Loss 1.9410 (1.9410)	Prec@1 44.000 (44.000)	Prec@3 76.000 (76.000)**
THCudaCheck FAIL file=/pytorch/aten/src/THC/generic/THCStorage.cu line=58 error=2 : out of memory
Traceback (most recent call last):
  File "main_single_gpu.py", line 362, in <module>
    main()
  File "main_single_gpu.py", line 192, in main
    prec1 = validate(val_loader, model, criterion)
  File "main_single_gpu.py", line 286, in validate
    output = model(input_var)
  File "/root/anaconda3/envs/pn-pytorch/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/ml/G/panna/two-stream-pytorch-master/models/flow_resnet.py", line 154, in forward
    x = self.layer3(x)
  File "/root/anaconda3/envs/pn-pytorch/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/envs/pn-pytorch/lib/python2.7/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/root/anaconda3/envs/pn-pytorch/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/ml/G/panna/two-stream-pytorch-master/models/flow_resnet.py", line 87, in forward
    out = self.conv3(out)
  File "/root/anaconda3/envs/pn-pytorch/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/envs/pn-pytorch/lib/python2.7/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/aten/src/THC/generic/THCStorage.cu:58

**Comment by bryanyzhu** [comment]
Hi, thank you for your interest. 

(1) For the OOM issue, maybe reduce the batch size a little bit and see. If it still comes up, then maybe there is memory leakage problem. We can investigate more on the problem. 

(2) For multi-GPU, I think it is straightforward to extend. Just make 

`model = torch.nn.DataParallel(model).cuda()`

And it should work. But pay attention to batch size, the total batch size should be less than 256, otherwise maybe there is diverge problem.
