### ISSUE TITLE
Stuck there when I run "python main_single_gpu.py datasets/"

### ISSUE THREAD

**Issue by ntuyt** [bryanyzhu/two-stream-pytorch#4]
2017-09-21 04:19:56,066 - INFO - Building model ... 
/home/ytan/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py:360: UserWarning: src is not broadcastable to dst, but they have the same number of elements.  Falling back to deprecated pointwise behavior.
  own_state[name].copy_(param)
2017-09-21 04:20:14,050 - INFO - Model flow_vgg16 is loaded. 
2017-09-21 04:20:14,051 - INFO - Saving everything to directory ./checkpoints.
2017-09-21 04:20:14,100 - INFO - 13320 samples found, 9537 train samples and 3783 test samples.
2017-09-21 04:20:14,100 - INFO - 0.005
Could not load file datasets/JumpingJack/v_JumpingJack_g25_c04/flow_x_00029.jpg or datasets/JumpingJack/v_JumpingJack_g25_c04/flow_y_00029.jpg
Could not load file datasets/CliffDiving/v_CliffDiving_g17_c01/flow_x_00060.jpg or datasets/CliffDiving/v_CliffDiving_g17_c01/flow_y_00060.jpg
Could not load file datasets/RopeClimbing/v_RopeClimbing_g17_c05/flow_x_00074.jpg or datasets/RopeClimbing/v_RopeClimbing_g17_c05/flow_y_00074.jpg
Could not load file datasets/PlayingSitar/v_PlayingSitar_g24_c07/flow_x_00186.jpg or datasets/PlayingSitar/v_PlayingSitar_g24_c07/flow_y_00186.jpg
/////////////////////////////////////////////////////////////////////////
It just stops here and do not have any progress.

**Comment by bryanyzhu** [comment]
Hi, there. The thing is, you may not have those optical flow images as I have. 

As I wrote in [here](https://github.com/bryanyzhu/two-stream-pytorch/blob/master/datasets/ucf101.py#L48-L49), if the code couldn't find the optical flow images,  the program will stop and exit. So that is why no progress. 

I suggest you change the setting files, e.g., train_flow_split1.txt according to your situation. Usually due to different video codec, we may have different number of RGB or optical flow images.

**Comment by ntuyt** [comment]
Thanks so much for your fast reply. Get it.

**Comment by ntuyt** [comment]
Hello, I add the data files but it reports below errors, do you have any suggestions?


python main_single_gpu.py datasets/ucfnew
2017-09-24 08:46:46,667 - INFO - Building model ... 
2017-09-24 08:47:05,368 - INFO - Model rgb_vgg16 is loaded. 
2017-09-24 08:47:05,369 - INFO - Saving everything to directory ./checkpoints.
2017-09-24 08:47:05,369 - INFO - reach here
2017-09-24 08:47:05,494 - INFO - 13320 samples found, 9537 train samples and 3783 test samples.
2017-09-24 08:47:05,494 - INFO - 0.005
2017-09-24 08:47:05,495 - INFO - reach here
Traceback (most recent call last):
  File "main_single_gpu.py", line 368, in <module>
    main()
  File "main_single_gpu.py", line 190, in main
    train(train_loader, model, criterion, optimizer, epoch)
  File "main_single_gpu.py", line 232, in train
    for i, (input, target) in enumerate(train_loader):
  File "/home/ytan/miniconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 201, in __next__
    return self._process_next_batch(batch)
  File "/home/ytan/miniconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 221, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "/home/ytan/miniconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 40, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/ytan/miniconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 109, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/home/ytan/miniconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 109, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/home/ytan/miniconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 89, in default_collate
    storage = batch[0].storage()._new_shared(numel)
  File "/home/ytan/miniconda3/lib/python3.6/site-packages/torch/storage.py", line 113, in _new_shared
    return cls._new_using_fd(size)
RuntimeError: unable to write to file </torch_25231_36990222> at /opt/conda/conda-bld/pytorch_1503970438496/work/torch/lib/TH/THAllocator.c:271

**Comment by bryanyzhu** [comment]
Sorry, I don't know why such error occurs. I think it maybe due to different version of python or pytorch. I am modifying my code right now to achieve good accuracy on flow stream. I will test on different versions of pytorch to see if I can reproduce your errors.

**Comment by ntuyt** [comment]
Hi, Zhu

Thanks so much for your reply.

Get it.

Best,

Tan

________________________________
