### ISSUE TITLE
Errors about imput.size[1]

### ISSUE THREAD

**Issue by Blankit** [bryanyzhu/two-stream-pytorch#7]
Hello. when I run ' main_single_gpu.py' with rgb frames, I met mistakes as follows:

```
Traceback (most recent call last):
  File "/home/zxf/Desktop/learn/reference/two-stream-pytorch/main_single_gpu.py", line 357, in <module>
    main()
  File "/home/zxf/Desktop/learn/reference/two-stream-pytorch/main_single_gpu.py", line 182, in main
    train(train_loader, model, criterion, optimizer, epoch)
  File "/home/zxf/Desktop/learn/reference/two-stream-pytorch/main_single_gpu.py", line 229, in train
    output = model(input_var)
  File "/home/zxf/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zxf/Desktop/learn/reference/two-stream-pytorch/models/rgb_vgg16.py", line 30, in forward
    x = self.features(x)
  File "/home/zxf/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zxf/anaconda2/lib/python2.7/site-packages/torch/nn/modules/container.py", line 67, in forward
    input = module(input)
  File "/home/zxf/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zxf/anaconda2/lib/python2.7/site-packages/torch/nn/modules/conv.py", line 254, in forward
    self.padding, self.dilation, self.groups)
  File "/home/zxf/anaconda2/lib/python2.7/site-packages/torch/nn/functional.py", line 52, in conv2d
    return f(input, weight, bias)
RuntimeError: Need input.size[1] == 3 but got 30 instead.
```

The input.size is  (2L, 30L, 224L, 224L). Every videos' 10 frames are fed to VGG, then the net cannot deal with the input.

**Comment by zswzifir** [comment]
I have the same issue, I wonder how solve it? 
from the forward function in rgb_vgg16, it need to transform  (2L, 30L, 224L, 224L) into (20, 3, 224, 224), but the code did not do this, so i want to konw how the authers solve it , thanks.

**Comment by zswzifir** [comment]
I have read the code, it just can deal with the frms with new_length=1, i do not think it is the good method to handle the actions, when read flow stream, i think it is wrong, when new-length = 15, the input should be (2, 15*10*2,224,224), and transform in to (30,  20, 224, 224), then combine before softmax layer. So that this code just img classification, cannot extract temporal information.

**Comment by bryanyzhu** [comment]
Hi thanks for bringing up the issue. I am out of town now and will debug into it this weekend. It should handle temporal information because I test it when I released the code. Maybe some later commits broke it. Sorry about that, I will fix it asap.

**Comment by zswzifir** [comment]
It dosen't matter, but thank you for release the code.

**Comment by jhlee301** [comment]
During test the code, I have same issue that the dimension of VGG is not fit.
I hope you solve this problem as soon as possible.
Thanks!

**Comment by bryanyzhu** [comment]
@zswzifir @jangho2001us @Blankit I updated the codebase, hopefully the issue is solved. I didn't notice such error when i run my experiments. So just let me know if the issue still exists.

**Comment by jhlee301** [comment]
@bryanyzhu Thanks bryanyzhu. I really appreciate for your prompt action!
